export const quotes = {
    "work": [
      { frase: "El éxito no es el resultado de un esfuerzo aislado, sino de la perseverancia constante.", autor: "Anónimo" },
      { frase: "Cada pequeño paso que das te acerca más a tu meta.", autor: "Anónimo" },
      { frase: "La clave del éxito está en no rendirse nunca, incluso cuando las cosas se ponen difíciles.", autor: "Anónimo" },
      { frase: "El trabajo duro supera al talento cuando el talento no trabaja duro.", autor: "Kevin Durant" },
      { frase: "Cualquier progreso es progreso. No subestimes los pequeños logros.", autor: "Anónimo" },
      { frase: "Haz lo que amas y nunca tendrás que trabajar un día en tu vida.", autor: "Confucio" },
      { frase: "La disciplina es el puente entre las metas y los logros.", autor: "Jim Rohn" },
      { frase: "La verdadera medida del éxito es la persistencia en alcanzar tus sueños.", autor: "Anónimo" },
      { frase: "El trabajo en equipo convierte lo imposible en posible.", autor: "Anónimo" },
      { frase: "No se trata de ser el mejor, se trata de ser mejor de lo que eras ayer.", autor: "Anónimo" },
      { frase: "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", autor: "Robert Collier" },
      { frase: "Las oportunidades no llegan solas, hay que buscarlas.", autor: "Anónimo" },
      { frase: "No te detengas cuando estés cansado, detente cuando hayas terminado.", autor: "Anónimo" },
      { frase: "El mayor error que puedes cometer es no intentarlo.", autor: "Anónimo" },
      { frase: "Hazlo con pasión o no lo hagas en absoluto.", autor: "Anónimo" },
      { frase: "La motivación te lleva a comenzar, pero el hábito te permite continuar.", autor: "Jim Ryun" },
      { frase: "El esfuerzo es el camino más corto hacia el éxito.", autor: "Anónimo" },
      { frase: "La creatividad no es un talento, es una habilidad que se puede aprender.", autor: "Anónimo" },
      { frase: "Toma cada desafío como una oportunidad para crecer.", autor: "Anónimo" },
      { frase: "Las metas no se alcanzan sin acción.", autor: "Anónimo" },
      { frase: "Cada día es una nueva oportunidad para mejorar.", autor: "Anónimo" },
      { frase: "El éxito pertenece a aquellos que están dispuestos a dar más de lo que los demás dan.", autor: "Anónimo" },
      { frase: "Cree en ti mismo, porque si tú no lo haces, nadie más lo hará.", autor: "Anónimo" },
      { frase: "La diferencia entre lo que eres y lo que quieres ser es lo que haces.", autor: "Anónimo" },
      { frase: "Cuando te sientas tentado a rendirte, recuerda por qué empezaste.", autor: "Anónimo" },
      { frase: "No tengas miedo de renunciar a lo bueno para perseguir lo grandioso.", autor: "John D. Rockefeller" },
      { frase: "Si no te desafía, no te cambiará.", autor: "Anónimo" },
      { frase: "El fracaso no es el final, es solo un paso más hacia el éxito.", autor: "Anónimo" },
      { frase: "Cada esfuerzo que haces hoy te acerca a tus sueños.", autor: "Anónimo" },
      { frase: "El único lugar donde el éxito viene antes que el trabajo es en el diccionario.", autor: "Vidal Sassoon" }
    ],
    "family": [
      { frase: "La familia es el corazón de nuestra vida y la fuerza que nos impulsa a seguir adelante.", autor: "Anónimo" },
      { frase: "Un hogar lleno de amor es el lugar más seguro en el mundo.", autor: "Anónimo" },
      { frase: "Los momentos con la familia son los que realmente importan en la vida.", autor: "Anónimo" },
      { frase: "La familia es lo primero, lo demás puede esperar.", autor: "Anónimo" },
      { frase: "Cada día con mi familia es una bendición que no debe tomarse por sentada.", autor: "Anónimo" },
      { frase: "La verdadera riqueza está en el amor que compartimos con nuestros seres queridos.", autor: "Anónimo" },
      { frase: "La familia es un refugio, un lugar de paz y apoyo incondicional.", autor: "Anónimo" },
      { frase: "La unión de la familia es más fuerte que cualquier desafío que enfrente el mundo.", autor: "Anónimo" },
      { frase: "El amor familiar es el fundamento sobre el que construimos nuestros sueños.", autor: "Anónimo" },
      { frase: "En la familia, no importa cuán lejos llegues, siempre serás parte de algo grande.", autor: "Anónimo" },
      { frase: "El mejor regalo que podemos dar es nuestro tiempo y amor a quienes más queremos.", autor: "Anónimo" },
      { frase: "La familia no se mide por los lazos de sangre, sino por los lazos del corazón.", autor: "Anónimo" },
      { frase: "Cuando estamos juntos, todo es posible.", autor: "Anónimo" },
      { frase: "La familia es el pegamento que nos mantiene unidos, pase lo que pase.", autor: "Anónimo" },
      { frase: "Cuidar de la familia es una inversión en nuestra felicidad y bienestar.", autor: "Anónimo" },
      { frase: "El amor de una familia nunca se agota, solo crece con el tiempo.", autor: "Anónimo" },
      { frase: "La familia no es perfecta, pero el amor que nos une sí lo es.", autor: "Anónimo" },
      { frase: "Lo más importante en la vida no son las cosas materiales, sino los momentos con los que compartimos el corazón.", autor: "Anónimo" },
      { frase: "Una familia feliz es el reflejo de una vida llena de amor y respeto.", autor: "Anónimo" },
      { frase: "El hogar es donde empieza el amor y nunca termina.", autor: "Anónimo" },
      { frase: "No hay amor más fuerte que el amor de una madre, ni más sincero que el amor de un padre.", autor: "Anónimo" },
      { frase: "La familia es el primer lugar donde aprendemos a amar y a ser amados.", autor: "Anónimo" },
      { frase: "El apoyo de la familia es el mejor impulso para alcanzar nuestros sueños.", autor: "Anónimo" },
      { frase: "A veces, las palabras no son necesarias, solo estar juntos lo dice todo.", autor: "Anónimo" },
      { frase: "Nada puede reemplazar el amor y la compañía de una familia.", autor: "Anónimo" },
      { frase: "Las verdaderas bendiciones en la vida vienen de estar rodeado de la gente que amas.", autor: "Anónimo" },
      { frase: "El amor de la familia es el mayor de los tesoros.", autor: "Anónimo" },
      { frase: "No hay nada como el abrazo de un ser querido para sentir que todo estará bien.", autor: "Anónimo" },
      { frase: "La familia nos enseña que la verdadera felicidad está en las pequeñas cosas.", autor: "Anónimo" },
      { frase: "La familia es donde la vida comienza y el amor nunca termina.", autor: "Anónimo" }
    ],
    "study": [
      { frase: "El estudio constante es la llave que abre todas las puertas del conocimiento.", autor: "Anónimo" },
      { frase: "El aprendizaje nunca termina, siempre hay algo nuevo que descubrir.", autor: "Anónimo" },
      { frase: "Lo único que puede detenerte es la falta de esfuerzo.", autor: "Anónimo" },
      { frase: "El esfuerzo de hoy es la sabiduría de mañana.", autor: "Anónimo" },
      { frase: "La educación es el arma más poderosa para cambiar el mundo.", autor: "Nelson Mandela" },
      { frase: "Tu mente es un jardín, los estudios son las semillas que siembras.", autor: "Anónimo" },
      { frase: "El conocimiento es la base sobre la cual construimos nuestras vidas.", autor: "Anónimo" },
      { frase: "No hay límites para lo que puedes aprender si te lo propones.", autor: "Anónimo" },
      { frase: "El éxito académico no se mide por las calificaciones, sino por el esfuerzo y la perseverancia.", autor: "Anónimo" },
      { frase: "El estudio es el puente entre tus sueños y tus logros.", autor: "Anónimo" },
      { frase: "No hay atajos para el éxito, solo trabajo y dedicación.", autor: "Anónimo" },
      { frase: "El único lugar donde el éxito viene antes que el trabajo es en el diccionario.", autor: "Vidal Sassoon" },
      { frase: "La perseverancia es la clave para transformar el esfuerzo en éxito.", autor: "Anónimo" },
      { frase: "Aprender es un regalo, incluso cuando el dolor es tu maestro.", autor: "Anónimo" },
      { frase: "Los grandes logros comienzan con una decisión: aprender.", autor: "Anónimo" },
      { frase: "El conocimiento adquirido se convierte en poder cuando lo aplicas.", autor: "Anónimo" },
      { frase: "Cada libro leído es una nueva ventana al mundo.", autor: "Anónimo" },
      { frase: "Tu capacidad de aprender es tan ilimitada como tu disposición para estudiar.", autor: "Anónimo" },
      { frase: "Cada día que estudias es un paso más cerca de tus sueños.", autor: "Anónimo" },
      { frase: "No te detengas hasta estar orgulloso de lo que has logrado.", autor: "Anónimo" },
      { frase: "El fracaso es solo una oportunidad para comenzar de nuevo, con más experiencia.", autor: "Anónimo" },
      { frase: "La educación es el pasaporte para el futuro, el mañana pertenece a quienes se preparan hoy.", autor: "Malcolm X" },
      { frase: "Los grandes estudiantes no solo aprenden, también enseñan y comparten.", autor: "Anónimo" },
      { frase: "Cada pregunta que haces es una oportunidad de aprender algo nuevo.", autor: "Anónimo" },
      { frase: "El conocimiento es la herramienta más poderosa para transformar tu vida.", autor: "Anónimo" },
      { frase: "Los logros en el estudio son el reflejo de la disciplina y el compromiso.", autor: "Anónimo" },
      { frase: "El estudio no es un sacrificio, es una inversión en tu futuro.", autor: "Anónimo" },
      { frase: "La educación te da el poder de hacer cambios significativos en el mundo.", autor: "Anónimo" },
      { frase: "Cada desafío académico es solo una oportunidad disfrazada.", autor: "Anónimo" },
      { frase: "El éxito en los estudios se construye con paciencia, dedicación y amor por aprender.", autor: "Anónimo" }
    ]
};